name: "Compile Registry Package Sets"
on:
  schedule:
    - cron: '30 19 * * 4'
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: purifix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: compile packages
      run: nix run .#build-uncached .#packages.x86_64-linux.registry-package-sets
