name: "Build examples"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v21
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: purifix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#all-examples -L
      timeout-minutes: 25
